// @license
// Copyright (c) ggsuite
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/dna_audanika_version_test.dart.
// coverage:ignore-file

/// The version of the `dna_audanika` package.
const String dnaAudanikaVersion = '0.1.3';
